version: '3'
services:
  ml-metadata:
    image: gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
    container_name: mlmd-server
    ports:
      - "8080:8080"
    environment:
      - METADATA_STORE_SERVER_CONFIG_FILE=/tmp/shared/conn_config.pb
    volumes:
      - ./test/config/ml-metadata:/tmp/shared
  model-registry:
    image: quay.io/opendatahub/model-registry:latest
    command: ["proxy"]
    container_name: model-registry
    ports:
      - "8081:8080"
    depends_on: 
      - ml-metadata