[tool.poetry]
name = "model-registry"
version = "0.1.0"
description = "Client for Red Hat OpenDataHub Model Registry"
authors = ["Isabella Basso do Amaral <idoamara@redhat.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">= 3.9, < 3.11"
attrs = "^21.0"
ml-metadata = "^1.14.0"
typing-extensions = "^4.8"

[tool.poetry.group.dev.dependencies]
sphinx = "^7.2.6"
furo = "^2023.9.10"
myst-parser = { extras = ["linkify"], version = "^2.0.0" }
pytest = "^7.4.2"
coverage = { extras = ["toml"], version = "^7.3.2" }
pytest-cov = "^4.1.0"
sphinx-autobuild = "^2021.3.14"
ruff = "^0.1.6"
mypy = "^1.7.0"

[tool.coverage.run]
branch = true
source = ["model_registry"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119

[tool.ruff]
target-version = "py39"
select = [
    "F", # pyflakes
    # pycodestyle
    "W", # warnings
    "E", # errors

    "C90", # mccabe
    "B",   # bugbear
    "S",   # flake8-bandit

    "C4",  # flake8-comprehensions
    "D",   # pydocstyle
    "EM",  # flake8-errmsg
    "I",   # isort
    "PT",  # pytest
    "Q",   # flake8-quotes
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
]
respect-gitignore = true
ignore = [
    "D105", # missing docstring in magic method
    "E501", # line too long
    "S101", # use of assert detected
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"tests/**/*.py" = [
    "D", # missing docstring in public module
]

[tool.ruff.mccabe]
max-complexity = 8
