[tool.poetry]
name = "model-registry"
version = "0.1.0"
description = "Client for Red Hat OpenDataHub Model Registry"
authors = ["Isabella Basso do Amaral <idoamara@redhat.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">= 3.9, < 3.11"
attrs = "^21.0"
ml-metadata = "^1.14.0"
typing-extensions = "^4.8"

[tool.poetry.group.dev.dependencies]
sphinx = "^7.2.6"
furo = "^2023.9.10"
myst-parser = { extras = ["linkify"], version = "^2.0.0" }
pytest = "^7.4.2"
coverage = { extras = ["toml"], version = "^7.3.2" }
pytest-cov = "^4.1.0"

[tool.coverage.run]
branch = true
source = ["model_registry"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119

[tool.ruff]
target-version = "py39"
ignore = ["E501"]

[tool.ruff.mccabe]
max-complexity = 8
