// Package registry provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package registry

import (
	"time"
)

// Artifact defines model for Artifact.
type Artifact struct {
	Id *int64 	`json:"id,omitempty"`
	ModelVersionId *int64 	`json:"modelVersionId,omitempty"`
	Metadata *struct {
		Authority *string `json:"authority,omitempty"`
	} `json:"metadata,omitempty"`
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
	Uri  *string `json:"uri,omitempty"`
}

// Environment defines model for Environment.
type Environment struct {
	Name *string `json:"name,omitempty"`
	Uri  *string `json:"uri,omitempty"`
}

// RegisteredModel defines model for RegisteredModel.
type RegisteredModel struct {
	Id       *int64 					 `json:"id,omitempty"`
	Labels   *[]string         `json:"labels,omitempty"`
	Name     *string           `json:"name,omitempty"`
	Versions *[]VersionedModel `json:"versions,omitempty"`
}

// VersionedModel defines model for VersionedModel.
type VersionedModel struct {
	RegisteredModelId *int64 						 `json:"registeredModelId,omitempty"`
	Artifacts    *[]Artifact             `json:"artifacts,omitempty"`
	Author       *string                 `json:"author,omitempty"`
	CreatedDate  *time.Time              `json:"created date,omitempty"`
	Environments *[]Environment          `json:"environments,omitempty"`
	Id           *int64                 `json:"id,omitempty"`
	Labels       *[]string               `json:"labels,omitempty"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	ModelName    *string                 `json:"model_name,omitempty"`
	ModelUri     string                  `json:"model_uri"`

	// Origin For instance, the DSP id which realized the model
	Origin      *string    `json:"origin,omitempty"`
	Tags        *[]string  `json:"tags,omitempty"`
	UpdatedDate *time.Time `json:"updated date,omitempty"`
	Version     *string    `json:"version,omitempty"`
}

// DeleteEnvironmentsParams defines parameters for DeleteEnvironments.
type DeleteEnvironmentsParams struct {
	Name *interface{} `form:"name,omitempty" json:"name,omitempty"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	Name  *string `form:"name,omitempty" json:"name,omitempty"`
	Id    *string `form:"id,omitempty" json:"id,omitempty"`
	Tag   *string `form:"tag,omitempty" json:"tag,omitempty"`
	Label *string `form:"label,omitempty" json:"label,omitempty"`
}

// CreateEnvironmentJSONRequestBody defines body for CreateEnvironment for application/json ContentType.
type CreateEnvironmentJSONRequestBody = Environment

// PostModelsJSONRequestBody defines body for PostModels for application/json ContentType.
type PostModelsJSONRequestBody = VersionedModel

// PostModelsNameJSONRequestBody defines body for PostModelsName for application/json ContentType.
type PostModelsNameJSONRequestBody = VersionedModel

// PatchModelsNameVersionsVersionJSONRequestBody defines body for PatchModelsNameVersionsVersion for application/json ContentType.
type PatchModelsNameVersionsVersionJSONRequestBody = VersionedModel
