name: Build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "24.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install makefile dependencies
        run: make deps
      - name: Clean
        run: make clean
      - name: Build
        run: make build
      - name: Demonstrate problem1 of 2
        run: touch asd1
      - name: Demonstrate problem2 of 2
        run: touch asd2
      - name: Check if there are uncommitted file changes
        run: |
          clean=$(git status --porcelain)
          if [[ -z "$clean" ]]; then
              echo "Empty git status --porcelain: $clean"
          else
              echo "Uncommitted file changes detected: $clean"
              git diff
              exit 1
          fi
      - name: Unit tests
        run: make test
