name: run-robot-tests
run-name: Run Robot Framework tests
# Run workflow for every push to repository
on: [push]
# Define workflow jobs
jobs:
  # Job runs Robot Framework tests against locally build image from current code
  run-robot-tests:
    # Ubuntu latest is sufficient system for run
    runs-on: ubuntu-latest
    # Define steps of job
    steps:
      # Get checkout action to get this repository
      - uses: actions/checkout@v4
      # Install defined Python version to run Robot Framework tests
      - name: Install Python 3.9.x
        # Get setup-python action to install Python
        uses: actions/setup-python@v4
        with:
          # Set Python version to install
          python-version: '3.9'
          # Set architecture of Python to install
          architecture: 'x64'
      # Install required Python packages for running Robot Framework tests
      - name: Install required Python packages
        # Install required Python packages using pip
        run: pip install ml-metadata robotframework robotframework-requests pyyaml
      # Install model_registry Python package from current code
      - name: Install model_registry Python package
        # Install model_registry package as editable using pip
        run: pip install -e clients/python
      # Start docker compose with locally build image from current code
      - name: Start docker compose with local image
        # Start docker compose in the background
        run: docker compose -f docker-compose-local.yaml up --detach
      # Run Robot Framework tests against running docker compose
      - name: Run Robot Framework tests
        # Run Robot Framework tests from test/robot directory
        run: robot test/robot
      # Shutdown docker compose with locally build image from current code
      - name: Shutdown docker compose with local image
        # Shutdown docker compose running in the background
        run: docker compose -f docker-compose-local.yaml down